### ISSUE TITLE
Is there any chance that prisma-filter will work with nestjs ^10.0.2?

### ISSUE THREAD

**Issue by timseriakov** [chax-at/prisma-filter#11]
Hi, before I dive into the code, is there any chance that prisma-filter will work with nestjs ^10.0.2?

**Comment by Nkay** [comment]
yes, it definitely will, as we are still working with it :)

**Comment by Valerionn** [comment]
Looks like I forgot to update the readme when I added Nest 10 support in June last year - yeah, as Nkay said, it's fully supported and used internally by us as well :)

I've just updated the readme so there should be no more confusion.

**Comment by timseriakov** [comment]
Danke!
